../design/Microprocessor.v
../design/Core.v
../design/Fetch.v
../design/fetch_pipe.v
../design/Decode.v
../design/decode_pipe.v
../design/control_unit.v
../design/control_decoder.v
../design/type_decoder.v
../design/immediate_gen.v
../design/register_file.v
../design/Execute.v
../design/execute_pipe.v
../design/execute_forwarding.v
../design/alu.v
../design/adder.v
../design/branch.v
../design/mux1_2.v
../design/mux2_4.v
../design/program_counter.v
../design/memory_stage.v
../design/memstage_pipe.v
../design/Write_back.v
../design/data_memory_top.v
../design/data_memory.v
../design/wrapper_memory.v
../design/instruc_mem_top.v
../design/instruction_memory.v
